name: CI workflow

on: #Define the event triggers
  push:
    branches: [ "main" ] #Event 1: When someone pushes to the main branch
  pull_request:
    branches: [ "main" ] #Event 2: When someone makes a pull request

jobs:
  build: 
  #Build is the name of job number 1
    runs-on: ubuntu-latest 
    #Runner. In this case is a OS.
    container: python:3.9-slim 
    #Must have the same version than the python used during the development
    steps:
      # "checkout" refers to the process of copying the repository's 
      # code into the runner's filesystem
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests -vv --with-spec --spec-color --with-coverage --cover-erase --cover-package=service
